name: Click to say hi (workflow)

on:
  - workflow_dispatch

jobs:
  hello-world-job:
    name: hello-world-job 👋💼
    runs-on: ubuntu-latest
    steps:
      - name: Hello world-step 👋🚶‍♂️
        run: echo "Hello from workflow-dispatch🌏"